<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="Hughes" name="com.testing_properties.Sample_IRetry_Analyzer" tests="6" failures="1" timestamp="2022-03-01T15:49:18 IST" time="0.026" errors="0">
  <testcase name="demo2" time="0.002" classname="com.testing_properties.Sample_IRetry_Analyzer">
    <skipped/>
  </testcase> <!-- demo2 -->
  <system-out/>
  <testcase name="demo2" time="0.002" classname="com.testing_properties.Sample_IRetry_Analyzer">
    <failure type="java.lang.AssertionError" message="expected:&lt;10&gt; but was:&lt;5&gt;">
      <![CDATA[java.lang.AssertionError: expected:<10> but was:<5>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.testing_properties.Sample_IRetry_Analyzer.demo2(Sample_IRetry_Analyzer.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- demo2 -->
  <system-out/>
  <testcase name="demo2" time="0.003" classname="com.testing_properties.Sample_IRetry_Analyzer">
    <skipped/>
  </testcase> <!-- demo2 -->
  <system-out/>
  <testcase name="demo2" time="0.003" classname="com.testing_properties.Sample_IRetry_Analyzer">
    <skipped/>
  </testcase> <!-- demo2 -->
  <system-out/>
  <testcase name="demo2" time="0.000" classname="com.testing_properties.Sample_IRetry_Analyzer">
    <skipped/>
  </testcase> <!-- demo2 -->
  <system-out/>
  <testcase name="demo1" time="0.016" classname="com.testing_properties.Sample_IRetry_Analyzer"/>
  <system-out/>
</testsuite> <!-- com.testing_properties.Sample_IRetry_Analyzer -->
